### ISSUE TITLE
ResourceExhaustedError : OOM when allocating tensor with shape ...

### ISSUE THREAD

**Issue by mhjhamza** [jadarve/PyZED-stereo#2]
Hey,

I've just bought ZED stereo camera for object detection with tensorFlow trained model. 
And whenever I pass a frame from ZED camera to tensorflow, It crashes.
Meanwhile, the same code works perfectly when I pass a frame from simple 1080p camera.

Maybe It's due to the callback. Can we get sync frames from ZED camera?
Would you please help me resolve the issue?

**Comment by jadarve** [comment]
Hey,

Have you tried using the [Python wrappers](https://github.com/stereolabs/zed-python) provided by StereoLabs? I no longer have a ZED camera and cannot maintain this repository.

One possible reason you are getting the OOM error is because TensorFlow is allocating all the GPU memory avaiable. Try just giving it a fraction of the GPU memory and allow it to grow: https://www.tensorflow.org/tutorials/using_gpu

Cheers!
